### ISSUE TITLE
Too many scrollbars on the snippet view

### ISSUE THREAD

**Issue by albertorestifo** [LukyVj/menu-to-cross-icon#5]
![image](https://cloud.githubusercontent.com/assets/1037048/5961479/3547748a-a7dd-11e4-8208-60df11814e00.png)

I think it's self explanatory.

Chrome 41 on OSX 10.10.1

**Comment by LukyVj** [comment]
Wow, yes, it is. 
Thanks, I'll fix it :)

**Comment by LukyVj** [comment]
@albertorestifo Can you please try it now ? 
Thank you.

**Comment by LukyVj** [comment]
Well, it should be good. 
Issue closed.

**Comment by albertorestifo** [comment]
Nope, still the same. I also tried in Incognito mode (to rule out caching)

**Comment by LukyVj** [comment]
Have you tried to empty the cache or anything else ? 
A friend tried and it seems okay, I tried on browserstack with the config you told me and I don't see them neither, And I just tried on canary (  42.0.2291.0  ) and I don't see them neither. 

Are you using a windows emulating an OSX system ? I ask because of the scrollbar look.

![](http://puu.sh/fczR5/96fddff733.gif)

**Comment by albertorestifo** [comment]
Ahhhh! Got it! Because I have a mouse plugged in, I get ugly scrollbars in return from OSX

**Comment by LukyVj** [comment]
So, I assume the issue can be closed :)

**Comment by albertorestifo** [comment]
The problem being, I get too many of them:

![image](https://cloud.githubusercontent.com/assets/1037048/5968033/6c524e10-a813-11e4-976e-68e96f0e553c.png)

Setting `overflow-x: hidden` on the element `<pre data-type="...>` did the trick:

![image](https://cloud.githubusercontent.com/assets/1037048/5968057/b17ceac2-a813-11e4-9247-c0e629f10b4a.png)

The one on the center is with the `overflow-x` to `hidden`

Edit: also setting `overflow-y: auto` to the `<code>` element removes the empty vertical scrollbar
